In [1]:
import keras
from keras.datasets import boston_housing
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.layers.normalization import BatchNormalization

(X_train, y_train), (X_valid, y_valid) = boston_housing.load_data()

Using TensorFlow backend.


57344/57026 [==============================] - 0s 2us/step


In [3]:
X_train.shape

(404, 13)

In [4]:
X_train[0]

array([   1.23247,    0.     ,    8.14   ,    0.     ,    0.538  ,
          6.142  ,   91.7    ,    3.9769 ,    4.     ,  307.     ,
         21.     ,  396.9    ,   18.72   ])

In [5]:
X_valid[0]

array([  18.0846,    0.    ,   18.1   ,    0.    ,    0.679 ,    6.434 ,
        100.    ,    1.8347,   24.    ,  666.    ,   20.2   ,   27.25  ,
         29.05  ])

In [6]:
model = Sequential()

model.add(Dense(32, input_dim=13, activation='relu'))
model.add(BatchNormalization())

model.add(Dense(16, activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.2))

model.add(Dense(1, activation='linear'))

model.compile(loss='mean_squared_error', optimizer='adam')

model.fit(X_train, y_train,
         batch_size=8, epochs=32, verbose=1,
         validation_data=(X_valid, y_valid))

Train on 404 samples, validate on 102 samples
Epoch 1/32
404/404 [==============================] - 1s 1ms/step - loss: 586.7479 - val_loss: 583.0465
Epoch 2/32
404/404 [==============================] - 0s 336us/step - loss: 561.6585 - val_loss: 561.1626
Epoch 3/32
404/404 [==============================] - 0s 329us/step - loss: 533.2185 - val_loss: 545.3594
Epoch 4/32
404/404 [==============================] - 0s 338us/step - loss: 512.3996 - val_loss: 507.7560
Epoch 5/32
404/404 [==============================] - 0s 332us/step - loss: 484.2241 - val_loss: 461.4894
Epoch 6/32
404/404 [==============================] - 0s 331us/step - loss: 450.7603 - val_loss: 375.5781
Epoch 7/32
404/404 [==============================] - 0s 331us/step - loss: 412.0314 - val_loss: 297.1243
Epoch 8/32
404/404 [==============================] - 0s 330us/step - loss: 369.2083 - val_loss: 249.4677
Epoch 9/32
404/404 [==============================] - 0s 332us/step - loss: 333.8071 - val_loss: 193.7987
Ep

In [8]:
import numpy as np

In [9]:
model.predict(np.reshape(X_valid[42], [1, 13]))

array([[ 17.89472961]], dtype=float32)